#cloud-config

write_files:
  # Write the .env file
  - path: /root/.env
    owner: root:root
    permissions: 0600
    content: |
      AWS_DEFAULT_REGION=${aws_default_region}
      ARTIFACTS_S3_BUCKET=${artifacts_s3_bucket}
      REPO_S3_BUCKET=${repo_s3_bucket}

# Update packages (except kernel)
repo_update: true
repo_upgrade: all

# Install packages
packages:
  # Required for mounting EFS volumes
  - docker
  - git

runcmd:
  - systemctl start --no-block docker.service
  - git clone https://github.com/kriansa/pve-kernel-builder.git /root/pve-kernel-builder

    # Move the .env to the build folder
  - mv /root/.env /root/pve-kernel-builder

    # Build the image
  - cd /root/pve-kernel-builder && make pull-image build > /var/log/kernel-builder.log 2>&1

    # Now move the logs to the S3, then shutdown
  - aws s3 cp /var/log/kernel-builder.log s3://${artifacts_s3_bucket}/kernel-builder/build-$(date '+%Y-%m-%dT%H:%I:%S%Z').log
  - poweroff
