#cloud-config

write_files:
  # Write the .env file
  - path: /root/.env
    owner: root:root
    permissions: 0600
    content: |
      AWS_DEFAULT_REGION=${aws_default_region}
      ARTIFACTS_S3_BUCKET=${artifacts_s3_bucket}
      REPO_S3_BUCKET=${repo_s3_bucket}

# Update packages (except kernel)
repo_update: true
repo_upgrade: all

# Install packages
packages:
  # Required for mounting EFS volumes
  - docker
  - git

runcmd:
  - systemctl enable docker.service
  - systemctl start --no-block docker.service
  - git clone https://github.com/kriansa/pve-kernel-builder.git /root/pve-kernel-builder
  # - cd /root/pve-kernel-builder && mv ../.env . && make pull-image build
  # - poweroff
